### ISSUE TITLE
How to use the provider?

### ISSUE THREAD

**Issue by I3olle** [conradludgate/terraform-provider-spotify#1]
Hi,

I can see that you have a section abotu the installation and I vaguely remember tweaking some things for a provider back in TF v0.11 where I installed the provider locally or cached it somehow. But I can't find any info on this stuff nowadays and don't know how to use this provider. I tried the example in plain and got a

```
Error while installing hashicorp/spotify: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/spotify
```

Then I tried adding:
```
terraform {
  required_providers {
    spotify = {
      source  = "github.com/conradludgate/spotify"
    }
  }
}
```

Which lead to a:
```
The given source address "github.com/conradludgate/spotify" specifies a GitHub
repository rather than a Terraform provider. Refer to the documentation of the
provider to find the correct source address to use.
```

Somehow the official terraform documentation is leaving me hanging. Would you mind adding a section on terraform version constraints and how to tell terraform how to find the installed provider? Or link me to the official documentation describing it? I seem to be blind.

Thanks in advance. I am really keen on trying out this provider cause so far I manage my playlists via a script which is taking a veeeeery long time due to API calls per minute constraints and I'd love to see a TF provider in action.

**Comment by conradludgate** [comment]
Hi! Thanks for the interest. This was a random project that I thought would be funny and I did not intend at all that someone would actually want to use it.

Anyway, I'm happy to help, sorry for only just seeing this.

I'll have a quick play with the code again and see if I can get it to work, then I'll add another comment with detailed instructions

**Comment by conradludgate** [comment]
I've gone through the process of uploading this provider to Terraform's repository: https://registry.terraform.io/providers/conradludgate/spotify/latest You can use it by adding

```tf
terraform {
  required_providers {
    spotify = {
      source = "conradludgate/spotify"
      version = "0.1.1"
    }
  }
}
```

to your terraform configuration

**Comment by paultyng** [comment]
FYI we have a documentation generator too if you wanted to load some docs in to the registry as well: https://www.terraform.io/docs/registry/providers/docs.html#generating-documentation

**Comment by paultyng** [comment]
Also, very cool project, I love seeing people doing weird stuff with Terraform 😄

**Comment by conradludgate** [comment]
@paultyng Thanks for this! That's awesome :) I'll get right to documenting this!

**Comment by I3olle** [comment]
Wow, thank you for going through that process. This will be fun!
