### ISSUE TITLE
Error: The terraform-provider-spotify_v0.1.6 plugin crashed!

### ISSUE THREAD

**Issue by harsh896** [conradludgate/terraform-provider-spotify#13]
Hello

I have tried spotify terraform provider but it gives below error. I have also refered to [#11](https://github.com/conradludgate/terraform-provider-spotify/issues/11) issue and after running docker I opened the auth url and authorized it. But still it gives me the below error.

`╷
│ Error: Plugin did not respond
│ 
│   with data.spotify_search_track.by_artist,
│   on main.tf line 34, in data "spotify_search_track" "by_artist":
│   34: data "spotify_search_track" "by_artist" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-spotify_v0.1.6 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa908c6]

goroutine 42 [running]:
golang.org/x/oauth2.(*Token).Type(0x0, 0x0, 0xc00016c200)
	golang.org/x/oauth2@v0.0.0-20201208152858-08078c50e5b5/token.go:59 +0x26
golang.org/x/oauth2.(*Token).SetAuthHeader(0x0, 0xc00016c100)
	golang.org/x/oauth2@v0.0.0-20201208152858-08078c50e5b5/token.go:80 +0x32
main.(*transport).RoundTrip(0xc00029fb40, 0xc00016c100, 0xc00029fb40, 0x0, 0x0)
	github.com/conradludgate/terraform-provider-spotify/spotify.go:87 +0x5b
net/http.send(0xc00016c100, 0x1149dc0, 0xc00029fb40, 0x0, 0x0, 0x0, 0xc00000e278, 0x0, 0x1, 0x0)
	net/http/client.go:251 +0x454
net/http.(*Client).send(0xc000116810, 0xc00016c100, 0x0, 0x0, 0x0, 0xc00000e278, 0x0, 0x1, 0xc000032800)
	net/http/client.go:175 +0xff
net/http.(*Client).do(0xc000116810, 0xc00016c100, 0x0, 0x0, 0x0)
	net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	net/http/client.go:585
net/http.(*Client).Get(0xc000116810, 0xc0000420f0, 0x4e, 0xc0000ad380, 0x40e0f8, 0x20)
	net/http/client.go:474 +0xbe
github.com/zmb3/spotify.(*Client).get(0xc0003a4040, 0xc0000420f0, 0x4e, 0xe04fe0, 0xc0005ac520, 0x0, 0x0)
	github.com/zmb3/spotify@v0.0.0-20200525010707-bc712583571e/spotify.go:220 +0x6a
github.com/zmb3/spotify.(*Client).SearchOpt(0xc0003a4040, 0xc0001822b0, 0x10, 0x8, 0xc0000ad778, 0xc0001822b0, 0x10, 0xc0006bcc50)
	github.com/zmb3/spotify@v0.0.0-20200525010707-bc712583571e/search.go:138 +0x305
main.dataSourceSearchTrackRead(0xc000726e00, 0xf90740, 0xc0003a4040, 0xc000726e00, 0x0)
	github.com/conradludgate/terraform-provider-spotify/data_source_search_track.go:143 +0x4a6
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc000118360, 0xc0005ac260, 0xf90740, 0xc0003a4040, 0xc0004efb58, 0x1, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:403 +0x91
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc0001d6480, 0xc0000adaf8, 0xc0005ac260, 0xc0005ac260, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:451 +0x8f
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc000728588, 0x115bcb0, 0xc000712ea0, 0xc00018d9c0, 0xc000728588, 0xc000712ea0, 0xc0002dfba0)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:1036 +0x42d
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0xf5a6a0, 0xc000728588, 0x115bcb0, 0xc000712ea0, 0xc000188540, 0x0, 0x115bcb0, 0xc000712ea0, 0xc0006c61e0, 0x59)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3341 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00035fa40, 0x1164a18, 0xc000001680, 0xc00016c000, 0xc000096960, 0x16b1d70, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.34.0/server.go:1210 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00035fa40, 0x1164a18, 0xc000001680, 0xc00016c000, 0x0)
	google.golang.org/grpc@v1.34.0/server.go:1533 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000034320, 0xc00035fa40, 0x1164a18, 0xc000001680, 0xc00016c000)
	google.golang.org/grpc@v1.34.0/server.go:871 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.34.0/server.go:869 +0x1fd

Error: The terraform-provider-spotify_v0.1.6 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
`

**Comment by conradludgate** [comment]
Fixed in #15
