### ISSUE TITLE
Make darwin_amd64 version available

### ISSUE THREAD

**Issue by QuentinBtd** [conradludgate/terraform-provider-spotify#14]
Hello,

I was working to use your provider, but I'm using a MacBook Pro M1. I saw the provider isn't built for this platform. 

So I cloned your repo and build the provider.

How could I help you to make the `darwin_amd64` version of the provider available for all ?

**Comment by conradludgate** [comment]
Thanks for bringing this to my attention. `darwin_amd64` is provided but `darwin_arm64` (for M1) is not. I'm not sure why though. I'm using Goreleaser to build my artifacts and `darwin_arm64` seems like it should be being built. (maybe my version of goreleaser is out of date)

**Comment by conradludgate** [comment]
Updated goreleaser and released v0.1.7 with `darwin_arm64` :tada:

**Comment by QuentinBtd** [comment]
> Thanks for bringing this to my attention. `darwin_amd64` is provided but `darwin_arm64` (for M1) is not. I'm not sure why though. I'm using Goreleaser to build my artifacts and `darwin_arm64` seems like it should be being built. (maybe my version of goreleaser is out of date)

I'm so sorry. Maybe I was too tired when I wrote the issue.

Of course I was talking for `darwin_arm64` for M1.

Thanks you for the release !
