### ISSUE TITLE
auth_code: ExactlyOneOf cannot be set with Required

### ISSUE THREAD

**Issue by userbradley** [conradludgate/terraform-provider-spotify#2]
Hey Conrad,

Thanks for getting this one working! I think you may get some traffic on this as I posted it to reddit a while back.

I have tried to get this working but running in to an issue.

I have attached it below:

```
spotify_new on  master [!+?] 🏎💨 v0.13.4 default via  14GiB/16GiB | 976MiB/976MiB on ☁️  (us-east-1) took 6s 
➜ terraform init

Initializing the backend...

Initializing provider plugins...
- Using previously-installed conradludgate/spotify v0.1.3

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

spotify_new on  master [!+?] 🏎💨 v0.13.4 default via  14GiB/16GiB | 976MiB/976MiB on ☁️  (us-east-1) 
➜ terraform plan

Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
        * auth_code: ExactlyOneOf cannot be set with Required





spotify_new on  master [!+?] 🏎💨 v0.13.4 default via  14GiB/16GiB | 976MiB/976MiB on ☁️  (us-east-1) 

```

Not sure what to do here. I will drop you an email to my terraform github and you can let me know if I've gone wrong somewhere.

I ask as I really want to write a blog post for this as I love strange terraform providers!

**Comment by conradludgate** [comment]
Yeah I've just resurrected this from the dead hours ago. I ended up breaking the configuration in v0.1.2 but I intend to fix it in the morning! 

I'll close this and tag you once I've confirmed it's working again

**Comment by userbradley** [comment]
You my friend are a legend!!

Appreciate the hard work brother!

**Comment by conradludgate** [comment]
So I have everything fixed locally, and I've tested it quite a bit. Still a bit rough around the edges but I'll do a release soon. Still have more I want to work on though

**Comment by conradludgate** [comment]
@userbradley [Released](https://github.com/conradludgate/terraform-provider-spotify/releases/tag/v0.1.4)

See https://github.com/conradludgate/terraform-provider-spotify#how-to-use to see how the usage has changed
