### ISSUE TITLE
Error: could not perform search  while executing terraform plan

### ISSUE THREAD

**Issue by Rstar1998** [conradludgate/terraform-provider-spotify#29]
Hey guys I am getting the following error while executing terraform plan 

Error: could not perform search [[artist:"Dolly Parton"]]: Get "https://api.spotify.com/v1/search?limit=10&q=artist%3A%22Dolly+Parton%22&type=track": 404 page not found

What could be the reason for this error?

Here is my main.tf file :

```tf
terraform {
  required_providers {
    spotify = {
      version = "~> 0.1.5"
      source  = "conradludgate/spotify"
    }
  }
}


provider "spotify" {
  api_key = var.spotify_api_key
}

resource "spotify_playlist" "playlist" {
  name        = "Terraform"
  description = "This playlist was created by Terraform"
  public      = true

  tracks = [
    data.spotify_search_track.by_artist.tracks[0].id,
  ]
}

data "spotify_search_track" "by_artist" {
  artists = ["Dolly Parton"]
  #  album = "Jolene"
  #  name  = "Early Morning Breeze"
}
```

**Comment by conradludgate** [comment]
Can you update to the latest `0.2.5` version and see if it's still happening?

**Comment by conradludgate** [comment]
It's working for me on the latest version

note that the syntax for search changed slightly:
```tf
data "spotify_search_track" "by_artist" {
  artist = "Dolly Parton" // singular artist
  #  album = "Jolene"
  #  name  = "Early Morning Breeze"
}
```

**Comment by Rstar1998** [comment]
@conradludgate Thanks bro. Its working now. You can close this issue.
