### ISSUE TITLE
Hosted instance of spotify auth proxy

### ISSUE THREAD

**Issue by conradludgate** [conradludgate/terraform-provider-spotify#3]
I intend to make a hosted instance of the spotify auth proxy server so that it's as straight forward as possible to get started with this provider.

How I imagine it to work:

1. User signs up to proxy service (using spotify account)
2. Server creates the token, gets the user's spotify ID and saves it with the hash of a new API key
3. User is given the ID and API Key as well as a dashboard for how many times their API Key has been used (with failure attempts too)
4. From the dashboard, the user can revoke the API Key to get a new one

**Comment by userbradley** [comment]
I run a reverse proxy server at reverse.breadinfra.net, i'm more than happy to host the code for free if you're able to give me saucy clear instructions and also a list of possible sec issues.

Server runs ubuntu 18.04

if you decide you want me to host the code i'll create a custom URL we can point things to, or if you want to use your own domain just point the record as a cname to hosted.on.breadinfra.net

**Comment by conradludgate** [comment]
@userbradley thanks for the offer. Since it will require my Spotify client id and secret however, I'd rather host it on my own server.

However, I'm not going to stop you if you want to host your own fork :) I'm working on this here https://github.com/conradludgate/spotify-api (currently empty)

It should be pretty simple to host, I'll just have a docker-compose file that contains the database and server

**Comment by conradludgate** [comment]
Barebones implementation hosted here: https://spotify.conradludgate.com/
