### ISSUE TITLE
Support: Terraform does not see the state of songs added to a playlist in the webui

### ISSUE THREAD

**Issue by JamesAtTensure** [conradludgate/terraform-provider-spotify#30]
Using Terraform 1.0
Using Provider v0.2.5

Steps to reproduce: 
Create a playlist using the terraform provider
Add a track manually through the webui. 
Update the state with `terraform refresh` or try to apply it with `terraform apply`

Terraform returns no changes.

I thought it should attempt to delete the track that was added through the webui since the playlist was managed.
I checked the `terraform.tfstate`. I don't see the song added through the webui in there. [my playlist](https://github.com/JamesAtTensure/spotify-playlist)

**Comment by conradludgate** [comment]
Thanks for reporting. I'll see if I can reproduce it

**Comment by conradludgate** [comment]
Thanks. Not sure how I missed that, will need to see if I can beef up the tests a little. Fix coming out in 0.2.6 shortly
