### ISSUE TITLE
PEBKAC: Working with my playlist from another computer does not pull playlist state

### ISSUE THREAD

**Issue by JamesAtTensure** [conradludgate/terraform-provider-spotify#32]
So I was on my work laptop and wanted to add a song to the playlist. But after terraform init. All the songs were in the `terraform.tfstate` but the playlist wasn't. `terraform plan showed that it would create a new playlist. `terraform apply` created a second playlist with a new ID and the same name

Steps to reproduce:
* Clone your playlist repo to another computer. (different folder would probably work as well since the state is local)
* Get local authenticator working with the docker image
* `terraform init`
*  `terraform plan`

End result:
* plan output shows a whole new playlist to add

Expected result:
* no changes

**Comment by conradludgate** [comment]
This is expected behaviour of terraform. That's what the state file is for (keeping track of resources and their IDs). You can import a playlist into your new state though using `terraform import spotify_playlist.<my_playlist> <playlistID>`

**Comment by JamesAtTensure** [comment]
I see. I just realized the reason I normally don't see this behavior is
because I'm used to working with a remote saved state like a bucket. Please
tag user is dumb and close.
